kind: Service
apiVersion: v1
metadata:
  name: railsapp-service
spec:
  selector:
    app: railsapp-bowling
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000